@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(WebApp, "Web Application", Javascript and React, Biedt alle TripTop-functionaliteit aan gebruikers via hun browser)
Component(SignIn, Sign In Controller, Spring MVC Rest Controller, Staat gebruikers toe in te loggen)
component "TripTopService" as Service
component "UserRepository\n(Beheert gebruikersgegevens)" as UserRepo
component "TravelPlansRepository\n(Beheert reisplannen)" as PlansRepo
database "Database\n(Opgeslagen gebruiker- en reisdata)" as DB
component "E-mail Component\n(Beheert e-mail communicatie)" as Email
component "TravelMethods Component\n(Biedt transportopties)" as TravelMethods
component "DiningOptions Component\n(Beheert eetgelegenheden)" as DiningOptions
component "Hotel Component\n(Beheert accommodatieboekingen)" as Hotel
component "CarRental Component\n(Auto verhuurdiensten)" as CarRental
component "TravelGuide Component\n(Biedt activiteiten en ervaringen)" as TravelGuide

component "Booking.com / Airbnb API\n(Beheert accommodatieboekingen)" as BookingAPI
component "NS / Deutsche Bahn / KLM API\n(Biedt transportopties)" as TransportAPI
component "Sixt / Hertz API\n(Auto verhuurdiensten)" as RentalAPI
component "Tripadvisor / GetYourGuide API\n(Biedt activiteiten en ervaringen)" as GuideAPI
component "Takeaway / Eet.nu API\n(Eten bezorgen en restaurantboekingen)" as DiningAPI
component "Google / Microsoft / Airbnb Login Provider\n(Beheert authenticatie en inloggen van gebruikers)" as LoginProvider

WebApp --> SignIn
WebApp --> Service
Service --> UserRepo
Service --> PlansRepo
Service --> Email
Service --> TravelMethods
Service --> DiningOptions
Service --> Hotel
Service --> CarRental
Service --> TravelGuide

UserRepo --> DB
PlansRepo --> DB

TravelMethods --> TransportAPI
CarRental --> RentalAPI
DiningOptions --> DiningAPI
Hotel --> BookingAPI
TravelGuide --> GuideAPI
SignIn --> LoginProvider
@enduml
