@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Systeemcontextdiagram voor TripTop
SHOW_PERSON_PORTRAIT()

' Gebruikers (boven)
Person(Traveler, "Reiziger", "Plant, boekt en wijzigt reizen")
Person(TravelAgent, "Reisagent", "Ondersteunt reizigers bij boekingen")

' Systeem (midden)
System(TripTop, "TripTop Webapplicatie", "Beheert reisboekingen en gebruikersinteracties")

' Externe systemen (onder)
System_Ext(Booking, "Booking.com / Airbnb API", "Regelt accommodaties")
System_Ext(Transport, "NS / Deutsche Bahn / KLM API", "Biedt transportopties")
System_Ext(CarRent, "Sixt / Hertz API", "Autoverhuur")
System_Ext(Activities, "Tripadvisor / GetYourGuide API", "Activiteiten en bezienswaardigheden")
System_Ext(Food, "Takeaway / Eet.nu API", "Eten bestellen en restaurantreserveringen")
System_Ext(IdProvider, "Google / Microsoft / Airbnb loginprovider", "Authenticatie en gebruikerslogin")

' Positionering
Traveler -[hidden]-> TripTop
TravelAgent -[hidden]-> TripTop
TripTop -[hidden]-> Booking
TripTop -[hidden]-> Transport
TripTop -[hidden]-> CarRent
TripTop -[hidden]-> Activities
TripTop -[hidden]-> Food
TripTop -[hidden]-> IdProvider

' Relaties
Traveler -> TripTop : "Plant, boekt en wijzigt reizen"
TravelAgent -> TripTop : "Ondersteunt reizigers op verzoek"

TripTop -down-> Booking : "Boekt accommodaties"
TripTop -down-> Transport : "Boekt vervoer"
TripTop -down-> CarRent : "Boekt huurauto's"
TripTop -down-> Activities : "Boekt activiteiten"
TripTop -down-> Food : "Bestelt eten"
TripTop -down-> IdProvider : "Login en authenticatie"

@enduml