@startuml C4_Components
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(Frontend, "Frontend", "JavaScript/React", "Single Page Application die de gebruikersinterface levert")

' Backend Componenten
System_Boundary(Backend, "TripTop Backend") {
    Component(PaymentController, "PaymentController", "Service Layer", "Verwerkt betaallogica")
    Component(PaymentService, "PaymentService", "Service Layer", "Verwerkt betaallogica")
    Component(BetaalFacade, "BetaalFacade", "interface", "Interactie met betaalservice")

    Component(PaypalFacade, "PaypalFacade", "Facade", "Interactie met PayPal service")
    Component(InvoiceFacade, "InvoiceFacade", "Facade", "Interactie met factuurservice")

    Component(PaypalService, "PaypalService", "Service", "Afhandelen van PayPal-betalingen")
    Component(InvoiceService, "InvoiceService", "Service", "Afhandelen van factuurbetalingen")
}

' Externe systemen
System_Ext(PaypalApi, "PayPal", "Verwerkt PayPal betalingen")

' REST Relaties
Rel(Frontend, PaymentController, "Roept aan", "HTTP/JSON")

' Overige relaties
PaymentController --> PaymentService : "Maakt gebruik van"
PaymentService --> PaypalFacade : "Stuurt verzoeken naar"
PaymentService --> InvoiceFacade : "Stuurt verzoeken naar"
BetaalFacade <.. PaypalFacade : "Implementeert"
BetaalFacade <.. InvoiceFacade : "Implementeert"
PaypalFacade --> PaypalService : "Stuurt verzoeken naar"
InvoiceFacade --> InvoiceService : "Stuurt verzoeken naar"
PaypalService --> PaypalApi : "Vraagt betaling aan"

@enduml
