
@startuml

[*] --> PLANNED : New Activity

PLANNED -down-> PAID : paid
PLANNED -down-> NOTDOABLE : unavailable
PLANNED -down-> ARRANGED : reserved
PAID -right-> NOTDOABLE : unavailable
PAID -down-> DONE : executed
ARRANGED -left-> NOTDOABLE : unavailable
ARRANGED -down-> DONE : executed

@enduml