@startuml
skinparam classAttributeIconSize 0
title Class Diagram – Adapter pattern met interne JSON mapping


class BookingAPIClient {
    -hotelService: IHotelService
    +BookingAPIClient(hotelService: IHotelService)
    +useHotelService(latitude: double, longitude: double, amount: int): List<Map<String, Object>>
}

interface IHotelService {
    +fetchHotels(latitude: double, longitude: double, amount: int): List<Map<String, Object>>
}

class HotelAdapter {
    +fetchHotels(latitude: double, longitude: double, amount: int): List<Map<String, Object>>
}

BookingAPIClient --> IHotelService : depends on
HotelAdapter ..|> IHotelService : implements
PrototypeTrenAdapterPatternApplication --> BookingAPIClient : uses
@enduml