@startuml C4_Components
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

participant AuthController
participant AuthService
participant MicrosoftAuthAdapter
participant ExternalAPI

AuthController -> AuthService: requestService(serviceId, userId)
AuthService -> MicrosoftAuthAdapter: callService("auth", token)
MicrosoftAuthAdapter -> ExternalAPI: (Auth API request)

ExternalAPI --> MicrosoftAuthAdapter: (Auth API response)
MicrosoftAuthAdapter --> AuthService: mapResponseToDomainModel(response)

AuthService --> AuthController: return Response

@enduml
