@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' Definieer Gebruikers
Person(Traveler, "Reiziger", "Boekt en beheert reizen")
Person(TravelAgent, "Reisbureau", "Ondersteunt reizigers met boekingen")

' Definieer Systeem
System_Boundary(TripTop, "TripTop", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {

' Definieer Containers
Container(Frontend, "Frontend", "React, JavaScript", "Beheert reisboekingen en gebruikersinteracties")
Container(GatewayAPI, "GatewayAPI", "Spring Boot, Java", "Verwerkt API-aanvragen")
Container(Backend, "Backend", "Spring Boot, Java", "Verwerkt bedrijfslogica")
ContainerDb(Database, "Database", "MongoDB", "Bewaart gebruikers- en reisdata")
}

' Definieer Externe Systemen
System_Ext(Booking, "Booking.com / Airbnb API", "Beheert accommodatieboekingen")
System_Ext(Transport, "NS / Deutsche Bahn / KLM API", "Biedt transportopties")
System_Ext(CarRent, "Sixt / Hertz API", "Auto verhuurdiensten")
System_Ext(Activities, "Tripadvisor / GetYourGuide API", "Biedt activiteiten en ervaringen")
System_Ext(Food, "Takeaway / Eet.nu API", "Eten bezorgen en restaurantboekingen")
System_Ext(IdProvider, "Google / Microsoft / Airbnb login Provider", "Beheert authenticatie en inloggen van gebruikers")

' Relaties
Traveler -> Frontend : "Boekt en beheert reizen"
TravelAgent -> Frontend : "Ondersteunt reizigers met boekingen"
Frontend -> GatewayAPI : "Verstuurt HTTP-verzoek"
GatewayAPI -> Backend : "Verwerkt verzoek"
Backend -> Booking : "Boekt accommodaties"
Backend -> Transport : "Boekt transport"
Backend -> CarRent : "Boekt huurauto"
Backend -> Activities : "Boekt activiteiten"
Backend -> Food : "Bestelt eten"
Backend -> Database : "Leest/Schrijft"
Backend -> IdProvider : "Inloggen en authenticatie"

' Positionering
Traveler -[hidden]-> TripTop
TravelAgent -[hidden]-> TripTop
TripTop -[hidden]-> GatewayAPI
GatewayAPI -[hidden]-> Booking
GatewayAPI -[hidden]-> Transport
GatewayAPI -[hidden]-> CarRent
GatewayAPI -[hidden]-> Activities
GatewayAPI -[hidden]-> Food
GatewayAPI -[hidden]-> IdProvider

@enduml
