@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

Person(Traveler, "Reiziger", "Plannen en boeken van een reis")

System_Boundary(s1, "Triptop Applicatie") {

    Container(Frontend, "Frontend", "React, JavaScript", "De front-end applicatie waarmee de reiziger zijn reis kan plannen")
    Container(Backend, "Backend", "Spring Boot, Java", "Verwerkt aanvragen, beheert reisdata en voert logica uit")
    ContainerDb(Database, "Database", "Couchbase", "Slaat reisgegevens op zoals boekingen en gebruikersinformatie")
}

System_Ext(NS, "NS/Deutsche Bahn/KLM API", "Levert vervoersopties")

Rel(Traveler, Frontend, "Interageert met")
Rel(Frontend, Backend, "Verstuurt gebruikersgegevens")
Rel(Backend, Backend, Verifieert gebruikersbevoegdheden)
Rel(Backend, NS, "Vraagt reisopties op")
Rel(Backend, Database, "Leest/schrijft reisgegevens")
Rel(Backend, Frontend, Verstuurt reisgegevens)

@enduml
