@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

Person(Traveler, "Reiziger", "Plannen en boeken van een reis")

System_Boundary(s1, "Triptop Applicatie") {

    Container(Frontend, "Webapplicatie", "?", "De front-end applicatie waarmee de reiziger zijn reis kan plannen")
    Container(Backend, "Backend", "?", "Verwerkt aanvragen, beheert reisdata en voert logica uit")
    ContainerDb(Database, "Database", "?", "Slaat reisgegevens op zoals boekingen en gebruikersinformatie")
    Container(ApiGateway, "API Gateway", "?", "Behandelt alle API-verzoeken")
}

System_Ext(NS, "NS/Deutsche Bahn/KLM API", "Levert vervoersopties")

Rel(Traveler, Frontend, "Interactie met de webapplicatie")
Rel(Frontend, ApiGateway, "Verstuurt gegevens naar")
Rel(ApiGateway, Backend, Stuurt gegevens naar)
Rel(Backend, Backend, Controleert of gebruiker bevoegd is om te boeken)
Rel(Backend, NS, "Reisopties opvragen")
Rel(Backend, Database, "Leest/schrijft reisgegevens")
Rel(Backend, ApiGateway, Stuurt reisgegevens naar)
Rel(ApiGateway, Frontend, Stuurt reisgegevens naar)

@enduml
