@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

LAYOUT_TOP_DOWN()

Person(Traveler, "Reiziger", "Plannen en boeken van een reis")

System_Boundary(s1, "Triptop Applicatie") {
    Container(Frontend, "Frontend", "React, JavaScript", "De front-end applicatie waarmee de reiziger kan inloggen")
    Container(Backend, "Backend", "Spring Boot, Java", "Verwerkt aanvragen, beheert reisdata en voert logica uit")
    ContainerDb(Database, Database, Couchbase, Bewaart gebruikers- en reisgegevens)
}

System_Ext(IdentityProvider, "Identity Provider", "Regelt authenticatie")

Rel(Traveler, Frontend, "Interactie met de webapplicatie")

Rel(Frontend, Backend, "Verstuurt inlogverzoek")

Rel(Backend, IdentityProvider, Verstuurt e-mail van gebruiker)
Rel(IdentityProvider, Backend, "Verstuurt authenticatietoken")
Rel(Backend, Backend, Verifieert token)

Rel(Backend, Database, "Haalt gegevens op")

Rel(Backend, Frontend, Verstuurt gegevens)

Rel(Frontend, Frontend, Slaat token op)


@enduml
