graph TD
%% Define system (TripTop)
    subgraph "TripTop System"
        TripTop["TripTop Web Application \n (Manages trip bookings & user interactions)"]
    end

%% Users
    Traveler["Traveler
    ( Plans, books & modifies trips)"] -->|Plans, books, changes travel plans| TripTop
    TravelAgent["Travel Agent
    (Supports travelers with bookings)"] -->|Supports travelers when asked upon via| TripTop

%% External systems
TripTop -->|Books accommodations| Booking["Booking.com / Airbnb API
(Handles accommodation bookings)"]
TripTop -->|Books transport| Transport["NS / Deutsche Bahn / KLM API
(Provides transportation options)"]
TripTop  -->|Books car rental| CarRent["Sixt / Hertz API
(Car rental services)"]
TripTop -->|Books activities| Activities["Tripadvisor / GetYourGuide API
(Offers activities and experiences)"]
 TripTop -->|Orders food| Food["Takeaway / Eet.nu API
(Food delivery and restaurant bookings)"]
 TripTop-->|Login authentication| IdProvider["Google / Microsoft / Airbnb login Provider
(Handles authentication and user login)"]