@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

title Dynamic Diagram – Ophalen van een reisplan

Person(user, "Traveler")

Container(travelController, "TravelController", "Spring REST Controller", "Ontvangt HTTP-verzoeken")
Container(travelService, "TravelService", "Service", "Verwerkt reisaanvragen")
Container(Client, "Client", "Client", "Haalt gegevens op")
Container(adapter, "TravelApiAdapter", "Adapter", "Mapt externe API-data naar interne modellen")

Rel(user, travelController, "vraagt reisplan op", "HTTP")
Rel(travelController, travelService, "roept aan", "getTravelPlan(userId)")

Rel(travelService, Client, "haalt gegevens op", "fetchgegevens(benodigde parameters)")


Rel(Client, adapter, "geeft externalResponse", "JSON")
Rel(adapter, travelService, "geeft  model terug", "JSON")


' Antwoord terug naar controller
Rel(travelService, travelController, "geeft TravelPlan terug", "JSON")
Rel(travelController, user, "stuurt TravelPlan terug", "JSON")

@enduml